"use client";
import { Activity, ArrowUpRight, Check, ChevronRight, CircleDollarSign, Clock3, Command, GitBranch, MoreHorizontal, Pause, Plus, RotateCcw, Search, ShieldCheck, Sparkles, X } from "lucide-react";
import { executions, loopStages } from "@/lib/demo-data";
import type { ExecutionStatus } from "@/lib/workflows";
import { useWorkflowStudio } from "../_hooks/use-workflow-studio";

const statusLabel: Record<ExecutionStatus, string> = { completed: "Completed", running: "Running", failed: "Failed", waiting: "Approval" };
export function StudioDashboard() {
 const studio = useWorkflowStudio(); const selected = executions.find(x => x.id === studio.selectedRun) ?? executions[0];
 return <main className="main"><header className="topbar"><div><p className="eyebrow">CONTROL PLANE / OVERVIEW</p><h1>Good morning, Panyakorn</h1><p>Monitor your agent workflows and act on what needs attention.</p></div><div className="header-actions"><button className="icon-button" aria-label="Search"><Search size={16}/></button><button className="primary"><Plus size={16}/>New workflow</button></div></header>
 <section className="metrics"><Metric icon={<GitBranch/>} title="Total workflows" value="12" delta="+2 this month"/><Metric icon={<Activity/>} title="Runs this month" value="1,842" delta="12.8% vs last month"/><Metric icon={<ShieldCheck/>} title="Success rate" value="97.6%" delta="1.2% improvement"/><Metric icon={<CircleDollarSign/>} title="Model spend" value="$184.20" delta="$0.10 / average run"/></section>
 <section className="content-grid"><div className="stack"><div className="section-head"><div><h2>Workflow operations</h2><p>Live automation health across your workspace</p></div><button className="ghost">View all <ArrowUpRight size={14}/></button></div><div className="toolbar"><div className="search"><Search size={14}/><input value={studio.query} onChange={e=>studio.setQuery(e.target.value)} placeholder="Search workflows..."/></div><div className="filters">{(["all","active","draft"] as const).map(s=><button key={s} className={studio.status===s?"selected":""} onClick={()=>studio.setStatus(s)}>{s}</button>)}</div></div><div className="workflow-list">{studio.filtered.map(w=><article className="workflow" key={w.id}><div className="workflow-icon"><GitBranch size={17}/></div><div className="workflow-main"><div className="workflow-title"><h3>{w.name}</h3><span className={`badge ${w.status}`}>{w.status}</span></div><p>{w.description}</p><div className="node-flow">{w.nodes.map((n,i)=><span key={n}><b>{n}</b>{i<w.nodes.length-1&&<ChevronRight size={12}/>}</span>)}</div></div><div className="workflow-stats"><strong>{w.success}%</strong><small>{w.runs.toLocaleString()} runs</small><time>{w.updated}</time></div><button className="more" aria-label="Workflow menu"><MoreHorizontal size={17}/></button></article>)}</div></div>
 <aside className="run-panel"><div className="panel-head"><div><span className="live-dot"/>LIVE EXECUTION</div><button className="more"><MoreHorizontal size={17}/></button></div><h2>{selected.id}</h2><p>{selected.workflow}</p><div className="run-meta"><span><Clock3 size={13}/>{selected.duration}</span><span><CircleDollarSign size={13}/>${selected.cost.toFixed(2)}</span></div><div className="timeline">{loopStages.map((stage,i)=><div className={`stage ${stage.state}`} key={stage.name}><div className="stage-rail"><span>{stage.state==="done"?<Check size={12}/>:stage.state==="running"?<RotateCcw size={12}/>:i+1}</span>{i<loopStages.length-1&&<i/>}</div><div><strong>{stage.name}</strong><p>{stage.detail}</p>{stage.state==="running"&&<div className="progress"><b/></div>}</div></div>)}</div><div className="approval"><div><ShieldCheck size={16}/><strong>Approval gate</strong></div><p>Publishing remains blocked until a reviewer approves the generated assets.</p><button>Open approval queue <ArrowUpRight size={13}/></button></div><div className="run-actions"><button><Pause size={14}/>Pause</button><button className="danger"><X size={14}/>Cancel run</button></div></aside></section>
 <section className="executions"><div className="section-head"><div><h2>Recent executions</h2><p>Inspect status, latency, and spend per run</p></div><button className="ghost">All executions <ArrowUpRight size={14}/></button></div><div className="table"><div className="tr th"><span>Run</span><span>Workflow</span><span>Status</span><span>Started</span><span>Duration</span><span>Cost</span></div>{executions.map(run=><button className={`tr ${studio.selectedRun===run.id?"selected-row":""}`} onClick={()=>studio.setSelectedRun(run.id)} key={run.id}><span className="mono">{run.id}</span><span>{run.workflow}</span><span><i className={`status ${run.status}`}/>{statusLabel[run.status]}</span><span>{run.started}</span><span className="mono">{run.duration}</span><span className="mono">${run.cost.toFixed(2)}</span></button>)}</div></section>
 <footer><span><Sparkles size={13}/>Studio demo environment</span><span>All systems operational</span><span><Command size={12}/> Command menu</span></footer></main>
}
function Metric({icon,title,value,delta}:{icon:React.ReactNode;title:string;value:string;delta:string}){return <article className="metric"><div className="metric-top"><span>{icon}</span><small>30D</small></div><p>{title}</p><strong>{value}</strong><div><ArrowUpRight size={12}/>{delta}</div></article>}
